apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
stringData:
  AUTH_DATABASE_URL: "postgres://<DB_USER>:<DB_PASSWORD>@<ENDPOINT_RDS_AUTH>:5432/auth_db?sslmode=require"
  FLAG_DATABASE_URL: "postgres://<DB_USER>:<DB_PASSWORD>@<ENDPOINT_RDS_FLAG>:5432/flags_db?sslmode=require"
  TARGETING_DATABASE_URL: "postgres://<DB_USER>:<DB_PASSWORD>@<ENDPOINT_RDS_TARGETING>:5432/targeting_db?sslmode=require"
  MASTER_KEY: "<MASTER_KEY_DA_APLICACAO>"
  SERVICE_API_KEY: "<SERVICE_API_KEY_INTERNA>"
